In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv('anies[06-01-2023].csv')
df2 = pd.read_csv('anies[06-02-2023].csv')
df3 = pd.read_csv('anies[06-03-2023].csv')
# df4 = pd.read_csv('anies[06-04-2023].csv')
df5 = pd.read_csv('anies[06-05-2023].csv')
df6 = pd.read_csv('anies[06-06-2023].csv')
df7 = pd.read_csv('anies[06-07-2023].csv')
df8 = pd.read_csv('anies[06-08-2023].csv')
df9 = pd.read_csv('anies[06-09-2023].csv')
df10 = pd.read_csv('anies[06-10-2023].csv')
df11 = pd.read_csv('anies[06-11-2023].csv')
df12 = pd.read_csv('anies[06-12-2023].csv')
df13 = pd.read_csv('anies[06-13-2023].csv')
df14 = pd.read_csv('anies[06-14-2023].csv')
# df15 = pd.read_csv('anies[06-15-2023].csv')
df16 = pd.read_csv('anies[06-16-2023].csv')
df17 = pd.read_csv('anies[06-17-2023].csv')
df18 = pd.read_csv('anies[06-18-2023].csv')
df19 = pd.read_csv('anies[06-19-2023].csv')
df20 = pd.read_csv('anies[06-20-2023].csv')
df21 = pd.read_csv('anies[06-21-2023].csv')
df22 = pd.read_csv('anies[06-22-2023].csv')
df23 = pd.read_csv('anies[06-23-2023].csv')
df24 = pd.read_csv('anies[06-24-2023].csv')
df25 = pd.read_csv('anies[06-25-2023].csv')
df26 = pd.read_csv('anies[06-26-2023].csv')
df27 = pd.read_csv('anies[06-27-2023].csv')
df28 = pd.read_csv('anies[06-28-2023].csv')
df29 = pd.read_csv('anies[06-29-2023].csv')
df30 = pd.read_csv('anies[06-30-2023].csv')

In [3]:
print('anies[06-01-2023] : ',df1.shape)
print('anies[06-02-2023] : ',df2.shape)
print('anies[06-03-2023] : ',df3.shape)
# print('anies[06-04-2023] : ',df4.shape)
print('anies[06-05-2023] : ',df5.shape)
print('anies[06-06-2023] : ',df6.shape)
print('anies[06-07-2023] : ',df7.shape)
print('anies[06-08-2023] : ',df8.shape)
print('anies[06-09-2023] : ',df9.shape)
print('anies[06-10-2023] : ',df10.shape)
print('anies[06-11-2023] : ',df11.shape)
print('anies[06-12-2023] : ',df12.shape)
print('anies[06-13-2023] : ',df13.shape)
print('anies[06-14-2023] : ',df14.shape)
# print('anies[06-15-2023] : ',df15.shape)
print('anies[06-16-2023] : ',df16.shape)
print('anies[06-17-2023] : ',df17.shape)
print('anies[06-18-2023] : ',df18.shape)
print('anies[06-19-2023] : ',df19.shape)
print('anies[06-20-2023] : ',df20.shape)
print('anies[06-21-2023] : ',df21.shape)
print('anies[06-22-2023] : ',df22.shape)
print('anies[06-23-2023] : ',df23.shape)
print('anies[06-24-2023] : ',df24.shape)
print('anies[06-25-2023] : ',df25.shape)
print('anies[06-26-2023] : ',df26.shape)
print('anies[06-27-2023] : ',df27.shape)
print('anies[06-28-2023] : ',df28.shape)
print('anies[06-29-2023] : ',df29.shape)
print('anies[06-30-2023] : ',df30.shape)

anies[06-01-2023] :  (83, 6)
anies[06-02-2023] :  (100, 6)
anies[06-03-2023] :  (100, 6)
anies[06-05-2023] :  (100, 6)
anies[06-06-2023] :  (100, 6)
anies[06-07-2023] :  (31, 6)
anies[06-08-2023] :  (100, 6)
anies[06-09-2023] :  (100, 6)
anies[06-10-2023] :  (100, 6)
anies[06-11-2023] :  (100, 6)
anies[06-12-2023] :  (100, 6)
anies[06-13-2023] :  (95, 6)
anies[06-14-2023] :  (100, 6)
anies[06-16-2023] :  (100, 6)
anies[06-17-2023] :  (81, 6)
anies[06-18-2023] :  (98, 6)
anies[06-19-2023] :  (100, 6)
anies[06-20-2023] :  (96, 6)
anies[06-21-2023] :  (100, 6)
anies[06-22-2023] :  (100, 6)
anies[06-23-2023] :  (95, 6)
anies[06-24-2023] :  (100, 6)
anies[06-25-2023] :  (100, 6)
anies[06-26-2023] :  (82, 6)
anies[06-27-2023] :  (79, 6)
anies[06-28-2023] :  (100, 6)
anies[06-29-2023] :  (100, 6)
anies[06-30-2023] :  (79, 6)

In [4]:
df_concat = pd.concat([df1, df2, df3, df5, df6, df7, df8, df9, df10, df11, df12, df13, df14, df16, df17, df18, df19, df20, df21, df22, df23, df24, df25, df26, df27, df28, df29, df30])
df_concat.shape
# df_concat

(2619, 6)

In [5]:
df_concat.to_csv('anies6.csv')
df_concat

,Unnamed: 0,id,date,text,place,screen_name
0,0,1664285223654420480,2023-06-01 14:58:12,RT @bianca01403: Iya bangeeeet. \n\nJurnalis N...,NaN,There91194264
1,1,1664285115575595008,2023-06-01 14:57:47,RT @ki_cakrasurya: Dulu Anies nyelenggarakan f...,NaN,SR21881
2,2,1664285099352006659,2023-06-01 14:57:43,RT @Jatayu_45: SEMOGA ANIES BASWEDAN MENDAPATK...,NaN,There91194264
3,3,1664285067324325889,2023-06-01 14:57:35,RT @Aceh: Menurut Survey Twitter @Aceh lebih d...,NaN,FahreziBadrun
4,4,1664284958343720961,2023-06-01 14:57:09,"RT @geloraco: Ahok Kalah di Pilkada Jakarta, j...",NaN,SahabatCel
...,...,...,...,...,...,...
74,74,1674773877057290240,2023-06-30 13:36:22,RT @aly_benzema: Demi menyelamatkan Indonesia ...,NaN,Darnatisma85066
75,75,1674773852113747969,2023-06-30 13:36:16,RT @Uwaisalatas: Melihat 2 foto sosok capres A...,NaN,Fasya59209847
76,76,1674773800817405952,2023-06-30 13:36:04,RT @republikaonline: Anies Baswedan diundang P...,NaN,Slash00713
77,77,1674773797684285440,2023-06-30 13:36:03,RT @Uwaisalatas: Melihat 2 foto sosok capres A...,NaN,BudiSut55037067
78,78,1674773787349508098,2023-06-30 13:36:01,RT @abwnews_: Anies Baswedan Jadi Tamu VIP Put...,NaN,Slash00713